service: boorran-node

provider:
  name: aws
  runtime: nodejs10.x

functions:
  start:
    handler: functions/index.handler
    events:
      - http:
          path: start
          method: get
  auth:
      handler: functions/Shared/Auth/index.handler
      events:
        - http:
            path: auth
            method: post
  boorranOrders:
    handler: functions/Boorran/SyncOrders/index.handler
    events:
      - http:
          path: /boorran/orders
          method: get

plugins:
  - serverless-offline
